FROM golang:1.26 AS builder
WORKDIR /src

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -trimpath -ldflags="-s -w" -o /out/mailwarden ./cmd/mailwarden

FROM gcr.io/distroless/static-debian12:nonroot
WORKDIR /app
COPY --from=builder /out/mailwarden /app/mailwarden
COPY configs /app/configs
COPY migrations /app/migrations

EXPOSE 8080 10031
ENTRYPOINT ["/app/mailwarden"]
CMD ["-config","/app/configs/mailwarden.example.yaml","-policy-config","/app/configs/policy.example.yaml"]
